#name: Metrics
#on:
#  schedule:
#    - cron: '38 */3 * * *'
#  push:
#    branches:
#      - main
#  workflow_dispatch:
#jobs:
#  github-metrics:
#    runs-on: ubuntu-latest
#    environment: 
#      name: production
#    permissions:
#      contents: write
#    steps:
#      - uses: lowlighter/metrics@latest
#        with:
#          token: ${{ secrets.METRICS_TOKEN }}
#
#          base: "header, repositories"
#
#          config_order: base.header, base.repositories, lines, languages, stars
#          config_timezone: America/New_York
#          config_padding: 10%

#          plugin_lines: yes
#          plugin_languages: yes
#          plugin_stars: yes
#          plugin_stars_limit: 3
